//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBMMS.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_codes
    {
        public project_codes()
        {
            this.documents = new HashSet<document>();
        }
    
        public string project_code { get; set; }
        public string project_name { get; set; }
        public int id_customer { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual ICollection<document> documents { get; set; }
    }
}
