//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBMMS.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string email { get; set; }
        public string pass { get; set; }
        public string user_name { get; set; }
        public int id_team { get; set; }
        public string sstem_user { get; set; }
        public string sstem_bat { get; set; }
    
        public virtual team team { get; set; }
    }
}
