//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBMMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class refers_codes
    {
        public string code { get; set; }
        public Nullable<int> id_team { get; set; }
        public string description { get; set; }
        public int id { get; set; }
    
        public virtual team team { get; set; }
    }
}
