//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBMMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public team()
        {
            this.users = new HashSet<user>();
            this.documents = new HashSet<document>();
            this.refers_codes = new HashSet<refers_codes>();
        }
    
        public int id { get; set; }
        public string team_name { get; set; }
    
        public virtual ICollection<user> users { get; set; }
        public virtual ICollection<document> documents { get; set; }
        public virtual ICollection<refers_codes> refers_codes { get; set; }
    }
}
