//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBMMS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ubmmsEntities : DbContext
    {
        public ubmmsEntities()
            : base("name=ubmmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<team> teams { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<project_codes> project_codes { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<log_documents> log_documents { get; set; }
        public DbSet<document> documents { get; set; }
        public DbSet<refers_codes> refers_codes { get; set; }
    }
}
